### ISSUE TITLE
Vin no throughout the site visible

### ISSUE THREAD

**Issue by phpsoftsol** [phpsoftsol/Design#7]
http://gls.dev.stickboycreative.com/web/index.php/vehicles/manage-events?id=2

user/pass: superadmin/superadmin

**Comment by phpsoftsol** [comment]
Vehicle status , must be visible 
http://gls.dev.stickboycreative.com/web/index.php/vehicle/save

Vin no: 1G1FG1R72G0106982

**Comment by pssanup** [comment]
select2.min.css


.select2-container .select2-selection--single

#select2-vehicle_id-7-container{
	padding:0px;
	color: #444;
	line-height: 28px;
}

.select2-container--krajee .select2-selection--single .select2-selection__arrow {
height: 26px;
}
